[env]
# Set Android NDK environment variables
ANDROID_NDK_HOME = { value = "$HOME/Android/Sdk/ndk/", relative = false }

# Target-specific configurations
[target.x86_64-linux-android]
linker = "x86_64-linux-android21-clang"
ar = "llvm-ar"

[target.aarch64-linux-android]
linker = "aarch64-linux-android21-clang"
ar = "llvm-ar"
